fail_fast: false
default_language_version:
  python: python3.10
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-json
      - id: check-toml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-github
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.8.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
