require("packer_init")
require("core.autocommands")
require("core.options")
require("core.keymaps")
require("core.colourscheme")
-- require("core.colourscheme_vscode")
require("plugins.completion")
require("plugins.lsp")
